# Introdução à Data Science com Python - Data ICMC-USP

Esse material foi desenvolvido pelo Data, grupo de extensão de aprendizado e ciência de dados compostos por alunos do Instituto de Ciências Matemáticas e de Computação da USP.

Esse notebook é acompanhado de um curso em video, que pode ser encontrado em [aqui](https://www.youtube.com/playlist?list=PLFE-LjWAAP9SfEuLXf3qrpw4szKWjlYq9)

Para saber mais sobre as atividades do Data entre no nosso site e nos siga e nossas redes sociais:
- [Site](http://data.icmc.usp.br/)
- [Twitter](https://twitter.com/data_icmc)
- [LinkedIn](https://www.linkedin.com/school/data-icmc/)
- [Facebook](https://www.facebook.com/dataICMC/)

Aproveite o material!

## Exercícios NumPy

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos nas aulas de NumPy. Esse material foi preparado para acompanhar o que foi passado nos videos, e em breve teremos a divulgação das resuluções com um vídeo de explicação.

In [1]:
# Importando a biblioteca
import numpy as np

### Arrays

In [5]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [ ]:
# Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta

In [ ]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23bb

In [ ]:
# Crie um array de uns com shape (4, 5)

In [ ]:
# Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)

In [ ]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]

### Indexando

In [13]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[24 15 12 26  3 22 12  1 45 32  1 40 47  9  4]


In [17]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
my_array[5:11]


array([22, 12,  1, 45, 32,  1])

In [18]:
# Selecione todos os elementos maiores que 20
maior_que_10 = my_array > 10
print(my_array)

print(maior_que_10)
print(my_array[maior_que_10])

[24 15 12 26  3 22 12  1 45 32  1 40 47  9  4]
[ True  True  True  True False  True  True False  True  True False  True
  True False False]
[24 15 12 26 22 12 45 32 40 47]


In [11]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [19]:
# Selecione o elemento na primeira linha da terceira coluna
my_matrix[0][2]

3

In [20]:
# Selecione o elemento na primeira linha da ultima coluna
my_matrix[0][-1]

4

In [59]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]
print(my_matrix[1:3,1:3])

[[ 6  7]
 [10 11]]


In [61]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]
print(my_matrix[0:2,1:4])

[[2 3 4]
 [6 7 8]]


In [62]:
# Selecione os elementos da ultima coluna inteira
my_matrix[-1][-1]

16

In [65]:
# Selecione os elementos da 2a linha inteira
my_matrix[1,:]

array([5, 6, 7, 8])

### Operações

In [ ]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

In [ ]:
# Some 10 a todos os elementos de my_array

In [ ]:
# Multiplique todos os elementos de my_array por 4

In [ ]:
# Obtenha a soma de todos os elementos de my_array

In [ ]:
# Obtenha a média de todos os elementos de my_array

In [ ]:
# Obtenha o indice do maior elemento de my_array

In [ ]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

In [ ]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

In [ ]:
# Some my_array elemento por elemento em cada linha de my_other_array

In [ ]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

In [ ]:
# Faça a multiplicação entre my_other_array e my_array

In [ ]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)

In [ ]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

In [ ]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)

In [ ]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [ ]:
# Gere a array anterior usando np.arange e a função reshape