# Introdução à Data Science com Python - Data ICMC-USP

Esse material foi desenvolvido pelo Data, grupo de extensão de aprendizado e ciência de dados compostos por alunos do Instituto de Ciências Matemáticas e de Computação da USP.

Esse notebook é acompanhado de um curso em video, que pode ser encontrado em [aqui](https://www.youtube.com/playlist?list=PLFE-LjWAAP9SfEuLXf3qrpw4szKWjlYq9)

Para saber mais sobre as atividades do Data entre no nosso site e nos siga e nossas redes sociais:
- [Site](http://data.icmc.usp.br/)
- [Twitter](https://twitter.com/data_icmc)
- [LinkedIn](https://www.linkedin.com/school/data-icmc/)
- [Facebook](https://www.facebook.com/dataICMC/)

Aproveite o material!

## Exercícios NumPy

O objetivo desse notebook é ajudar na fixação dos conteúdos que passamos nas aulas de NumPy. Esse material foi preparado para acompanhar o que foi passado nos videos, e em breve teremos a divulgação das resuluções com um vídeo de explicação.

In [1]:
# Importando a biblioteca
import numpy as np

### Arrays

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])

c = np.zeros((3,4))

In [5]:
# Pense em qual é a shape de cada um dos arrays acima
# Depois de pensar imprima cada um deles para conferir sua resposta
print (f'a = Shape 7, {a.shape}')
print (f'b = Shape 2,4{ b.shape}')
print (f'c = Shape 3,4 {c.shape}')

a = Shape 7, (7,)
b = Shape 2,4(2, 4)
c = Shape 3,4 (3, 4)


In [25]:
# Crie um array de uma dimenção com 20 elementos inteiros aletórios entre 0 e 23bb
array20 = np.random.randint(24, size = (20,))
print(len(array20))
print(array20)

20
[17 23 13 16 17 14 14 21  1  1  5 19  5 10  6  5 22 12 12 17]


In [33]:
# Crie um array de uns com shape (4, 5)
arrayzero = np.zeros([4,5])
print(arrayzero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
# Crie um array shape (4, 2) onde cada entrada vale 77
# (Dica: Talvez vc tenha que usar uma multiplicação)
array77 = np.ones([4,2])
print(array77 * 77)

[[77. 77.]
 [77. 77.]
 [77. 77.]
 [77. 77.]]


In [41]:
# Gere um array chamado my_sequence com os numeros 0, 10, 20, 30, ..., 90, 100]
my_sequence = np.zeros(11)
i = 0
for x in my_sequence:
    my_sequence[i] = i * 10
    i += 1
print(my_sequence)
for x in my_sequence:
    

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
0.0
10.0
20.0
30.0
40.0
50.0
60.0
70.0
80.0
90.0
100.0


### Indexando

In [13]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[24 15 12 26  3 22 12  1 45 32  1 40 47  9  4]


In [17]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)
my_array[5:11]


array([22, 12,  1, 45, 32,  1])

In [18]:
# Selecione todos os elementos maiores que 20
maior_que_10 = my_array > 10
print(my_array)

print(maior_que_10)
print(my_array[maior_que_10])

[24 15 12 26  3 22 12  1 45 32  1 40 47  9  4]
[ True  True  True  True False  True  True False  True  True False  True
  True False False]
[24 15 12 26 22 12 45 32 40 47]


In [11]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [19]:
# Selecione o elemento na primeira linha da terceira coluna
my_matrix[0][2]

3

In [20]:
# Selecione o elemento na primeira linha da ultima coluna
my_matrix[0][-1]

4

In [59]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]
print(my_matrix[1:3,1:3])

[[ 6  7]
 [10 11]]


In [61]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]
print(my_matrix[0:2,1:4])

[[2 3 4]
 [6 7 8]]


In [62]:
# Selecione os elementos da ultima coluna inteira
my_matrix[-1][-1]

16

In [65]:
# Selecione os elementos da 2a linha inteira
my_matrix[1,:]

array([5, 6, 7, 8])

### Operações

In [66]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[1 5 1 4 1]


In [67]:
# Some 10 a todos os elementos de my_array
print(my_array + 10)

[11 15 11 14 11]


In [68]:
# Multiplique todos os elementos de my_array por 4
print(my_array * 4)

[ 4 20  4 16  4]


In [69]:
# Obtenha a soma de todos os elementos de my_array
print(np.sum(my_array))

12


In [70]:
# Obtenha a média de todos os elementos de my_array
print(np.mean(my_array))

2.4


In [71]:
# Obtenha o indice do maior elemento de my_array
print(np.min(my_array))

1


In [76]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[2 2 0 0 3] 

[3 0 5 5 1]


In [ ]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

In [73]:
# Some my_array elemento por elemento em cada linha de my_other_array
print(my_array + my_other_array)

[3 3 7 8 8]


In [80]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[2 8 7 8]
 [7 5 6 8]
 [0 6 8 0]
 [8 1 9 3]
 [6 5 7 6]] 

[[2 2 9 2 2]
 [3 3 9 4 1]
 [9 4 5 7 3]
 [3 7 6 4 0]
 [4 5 3 4 6]
 [7 0 5 1 2]
 [0 7 5 9 1]
 [3 6 0 2 0]
 [3 6 2 2 4]
 [2 2 9 7 7]]


In [77]:
# Faça a multiplicação entre my_other_array e my_array
print(my_array * my_other_array)

[6 0 0 0 3]


In [82]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)

print(np.sum(my_other_array, axis=1))

[17 20 28 20 22 15 22 11 17 27]


In [83]:
my_array = np.random.randint(10, size=(5,4))
print(my_array)

[[9 7 4 3]
 [8 6 2 3]
 [5 9 2 8]
 [3 6 8 0]
 [1 5 2 8]]


In [92]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)
print(my_array.reshape(1,20))

[[9 7 4 3 8 6 2 3 5 9 2 8 3 6 8 0 1 5 2 8]]


In [93]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [103]:
# Gere a array anterior usando np.arange e a função reshape
a = np.arange(16)
a.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])