In [2]:
# Importando a biblioteca
import numpy as np

### Indexando

In [42]:
my_array = np.random.randint(50, size=(15,))
print(my_array)

[44 48 14 40 28 33 27 47 23  6 32 36  0 46 43]


In [44]:
# Selecione todos os elementos entre o quinto e o decimo primeiro (intervalo fechado)



array([33, 27, 47, 23,  6, 32, 36])

In [18]:
# Selecione todos os elementos maiores que 20


[24 15 12 26  3 22 12  1 45 32  1 40 47  9  4]
[ True  True  True  True False  True  True False  True  True False  True
  True False False]
[24 15 12 26 22 12 45 32 40 47]


In [11]:
my_matrix = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

In [19]:
# Selecione o elemento na primeira linha da terceira coluna


3

In [20]:
# Selecione o elemento na primeira linha da ultima coluna


4

In [59]:
# Selecione os elementos da matriz para obter o seguinte
# [[6, 7],
#  [10, 11]]


[[ 6  7]
 [10 11]]


In [61]:
# Selecione os elementos da matriz para obter o seguinte
# [[2, 3, 4],
#  [6, 7, 8]]


[[2 3 4]
 [6 7 8]]


In [62]:
# Selecione os elementos da ultima coluna inteira


16

In [65]:
# Selecione os elementos da 2a linha inteira


array([5, 6, 7, 8])

### Operações

In [3]:
my_array = np.random.randint(10, size=(5,))
print(my_array)

[7 3 2 0 6]


In [4]:
# Some 10 a todos os elementos de my_array
print(my_array + 10)

[17 13 12 10 16]


In [5]:
# Multiplique todos os elementos de my_array por 4
print(my_array * 4)

[28 12  8  0 24]


In [9]:
# Obtenha a soma de todos os elementos de my_array
print(my_array)
print(np.sum(my_array))

[7 3 2 0 6]
18


In [14]:
# Obtenha a média de todos os elementos de my_array
x = len(my_array)
y = np.sum(my_array)
print(y / x)
print(np.mean(my_array))

3.6
3.6


In [22]:
# Obtenha o indice do maior elemento de my_array
comp = 0
maior = 0
for x in my_array:
    if x > maior:
        maior = x
print(maior)
for x in my_array:
    if x == 7:
        print(f'O idndice de maior elemento é my_array[{comp}] = {maior}')
print(np.max(my_array))

7
O idndice maior elemento é my_array[0] = 7
7


In [23]:
my_array = np.random.randint(10, size=(5,))
my_other_array = np.random.randint(10, size=(5,))
print(my_array, '\n')
print(my_other_array)

[6 7 2 9 6] 

[7 8 1 4 9]


In [24]:
# Some my_array elemento por elemento em cada linha de my_other_array
print(my_array + my_other_array)

[13 15  3 13 15]


In [45]:
my_array = np.random.randint(10, size=(5,4))
my_other_array = np.random.randint(10, size=(10,5))
print(my_array, '\n')
print(my_other_array)

[[5 7 6 6]
 [4 3 6 7]
 [4 7 3 3]
 [9 8 9 6]
 [6 0 9 5]] 

[[1 4 0 2 3]
 [1 2 0 6 4]
 [7 9 7 5 3]
 [3 7 3 0 2]
 [6 2 4 9 3]
 [8 0 8 5 9]
 [0 7 5 0 5]
 [7 1 7 0 5]
 [0 8 4 4 2]
 [6 3 5 7 3]]


In [47]:
# Faça a multiplicação entre my_other_array e my_array
print(np.dot(my_array, my_other_array))

#print (my_array * my_other_array)

ValueError: shapes (5,4) and (10,5) not aligned: 4 (dim 1) != 10 (dim 0)

In [82]:
# Descubra a soma dos valores de cada linha de my_other_array
# (Dica: Pesquise sobre o atributo axis da função de soma)



[17 20 28 20 22 15 22 11 17 27]


[[9 7 4 3]
 [8 6 2 3]
 [5 9 2 8]
 [3 6 8 0]
 [1 5 2 8]]


In [92]:
# Usando reshape transforme a matriz acima em um vetor (Concatendo a linha de baixo na de cima)


[[9 7 4 3 8 6 2 3 5 9 2 8 3 6 8 0 1 5 2 8]]


In [93]:
np.array([[ 0,  1,  2,  3,  4,  5,  6,  7],
          [ 8,  9, 10, 11, 12, 13, 14, 15]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [103]:
# Gere a array anterior usando np.arange e a função reshape


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])