import numpy as np

# criar primeiro vetor
a = np.array([2,3,5,7,11]) 
a

#ndim número de dimensões do array
a.ndim

#shape formato do array
a.shape

b = np.array([[10, 20],
             [30, 40],
             [50,60]])
b

print(b.ndim)
print(b.shape)

 b[2,1]

b[1,0] = 23
b


#array com zeros
a = np.zeros((2,2))
a

#array com um
a = np.ones((3,3))
a

#random
a = np.random.random((3,2))
a

#randoint
a = np.random.randint(20, size=(3,3,3))
a

# vetor 
a = np.arange(5)
a

print(a)

a = np.random.randint(10, size = (5,))
a

print(a + 10)
print(a - 4)
print(a / 2)
print (a * 2)
print (a ** 2)
print (a + 10)
print (a <= 7)

a = np.random.randint(5, size = (5,))
b = np.random.randint(5, size= (5,))
print(a)
print(b)

print(a + b)
print(a * b)
print(a - b)
print(a // b)


#produto escalar
np.dot(a,b)

#matriz
a = np.random.randint(10, size = (3,4))
b = np.random.randint(10, size = (3,4))
print(a)
print("-=-=-=-=-")
print(b)

print(a + b)

#Multiplicar matrizes
c = np.random.randint(10, size = (4,2))
print(a)
print("-=-=-=-=-=-=-=")
print(c)
print(a.shape, c.shape)
print("-=-=-=-=-=-=-=")
print(np.dot(a,c))

#Matriz transposta
print(a)
print("-=-=-=-=-=-=-=-=")
print(a.T)

In [45]:
#Funçoes
a = np.random.randint(10, size =(5,))
print(a)

[4 4 2 4 4]


In [47]:
#soma, media
print(np.sum(a))
print(np.mean(a))

18
3.6


In [48]:
a = np.random.randint(10, size =(3,4))
print(a)


[[9 1 7 2]
 [0 5 4 4]
 [6 0 3 0]]


In [49]:
#soma colunas
np.sum(a, axis=1)

array([19, 13,  9])

In [50]:
#soma das linhas
np.sum(a, axis=0)

array([15,  6, 14,  6])

In [52]:
#reshape
a = np.random.randint(20 , size =(18,))
print(a)
print (np.shape(a))

[ 0  2  5  4 13  7 19  3 13 11 12  4 14  0 17  6  7  5]
(18,)


In [55]:
c = a.reshape(3,6)
print(c)

[[ 0  2  5  4 13  7]
 [19  3 13 11 12  4]
 [14  0 17  6  7  5]]
