In [3]:
import numpy as np

In [ ]:
# criar primeiro vetor
a = np.array([2,3,5,7,11]) 
a

In [4]:
#ndim número de dimensões do array
a.ndim

1

In [5]:
#shape formato do array
a.shape

(5,)

In [6]:
b = np.array([[10, 20],
             [30, 40],
             [50,60]])
b

array([[10, 20],
       [30, 40],
       [50, 60]])

In [8]:
print(b.ndim)
print(b.shape)

2
(3, 2)


In [9]:
 b[2,1]

60

In [10]:
b[1,0] = 23
b


array([[10, 20],
       [23, 40],
       [50, 60]])

In [12]:
#array com zeros
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [16]:
#array com um
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
#random
a = np.random.random((3,2))
a

array([[0.28367732, 0.10861223],
       [0.68347721, 0.81660295],
       [0.61320398, 0.93502853]])

In [21]:
#randoint
a = np.random.randint(20, size=(3,3,3))
a

array([[[ 4, 19, 17],
        [ 4, 11, 11],
        [18,  0, 18]],

       [[ 3, 16, 19],
        [ 5,  3, 17],
        [ 7,  6, 11]],

       [[ 4, 13, 15],
        [12,  9,  8],
        [ 0, 14,  0]]])

In [4]:
# vetor 
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [10]:
print(a)

[0 1 2 3 4]
